parserOptions:
  sourceType: 'module'

env:
  es6: true
  browser: true
  commonjs: true
  mocha: true

extends: 'htmlacademy/es6'
rules: {
  "no-return-assign": "off",
  "no-unused-expressions": "off",
  "no-invalid-this": "off",
  "consistent-return": "off",
  "curly": "off",
  "no-nested-ternary": "off"
}